export const API_PATH = {
  AUTH_LOGIN: "/auth/login",
  AUTH_LOGIN_WITH_ACCOUNT: "/auth/login-with-account",
  ORDER: "/order",
  ORDER_ID: (id: any) => `/order/${id}`,
  OFFER: "/offer",
  OFFER_ID: (id: any) => `/offer/${id}`,
  REPORT: "/report",
  ASSET: "/asset",
  ASSET_ID: (id: any) => `/asset/${id}`,
  CHANGE_STATUS_OFFER: (id: string) => `/offer/${id}/status`,
  SUBMIT_CODE_OFFER: (id: string) => `/offer/${id}/submit-code`,
  GET_INFO: "/auth/get-info",
  REGISTER_TELEGRAM: "/auth/register-telegram",
  OFFER_ONCHAIN: (id: string) => `/offer/${id}/submit-onchain`,
  FILL_OFFER: "/smart-contract/fill-offer",
  ADMIN_USERS: "/admin/user",
  ADMIN_OFFER_ID: (id: any) => `/offer/${id}/admin-delete`,
  CHANGE_STATUS_USER: (id: any) => `/admin/user/${id}/status`,
  FORCE_CANCEL_ORDER: (id: any) => `/order/${id}/force-cancel`,
  REPORT_DASHBOARD: "/general/reports",
  GENERAL_OFFERS: "/general/offers",
  GENERAL_USERS: "/general/users",
  GENERAL_ORDERS: "/general/orders",
  GENERAL_TICKETS: "/general/tickets",
  GENERAL_ORDER_TYPES: "/general/order/type",
  CHANGE_STATUS_REPORT: (id: string) => `/report/${id}/status`,
};
